# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robotica/roboime-control

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robotica/roboime-control

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robotica/roboime-control/CMakeFiles /home/robotica/roboime-control/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robotica/roboime-control/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named communication

# Build rule for target.
communication: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 communication
.PHONY : communication

# fast build rule for target.
communication/fast:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/build
.PHONY : communication/fast

#=============================================================================
# Target rules for targets named model

# Build rule for target.
model: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 model
.PHONY : model

# fast build rule for target.
model/fast:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/build
.PHONY : model/fast

#=============================================================================
# Target rules for targets named roboime-control

# Build rule for target.
roboime-control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roboime-control
.PHONY : roboime-control

# fast build rule for target.
roboime-control/fast:
	$(MAKE) -f CMakeFiles/roboime-control.dir/build.make CMakeFiles/roboime-control.dir/build
.PHONY : roboime-control/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/build
.PHONY : util/fast

src/communication/usb_worker.o: src/communication/usb_worker.cc.o
.PHONY : src/communication/usb_worker.o

# target to build an object file
src/communication/usb_worker.cc.o:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/src/communication/usb_worker.cc.o
.PHONY : src/communication/usb_worker.cc.o

src/communication/usb_worker.i: src/communication/usb_worker.cc.i
.PHONY : src/communication/usb_worker.i

# target to preprocess a source file
src/communication/usb_worker.cc.i:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/src/communication/usb_worker.cc.i
.PHONY : src/communication/usb_worker.cc.i

src/communication/usb_worker.s: src/communication/usb_worker.cc.s
.PHONY : src/communication/usb_worker.s

# target to generate assembly for a file
src/communication/usb_worker.cc.s:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/src/communication/usb_worker.cc.s
.PHONY : src/communication/usb_worker.cc.s

src/communication/zmq_worker.o: src/communication/zmq_worker.cc.o
.PHONY : src/communication/zmq_worker.o

# target to build an object file
src/communication/zmq_worker.cc.o:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/src/communication/zmq_worker.cc.o
.PHONY : src/communication/zmq_worker.cc.o

src/communication/zmq_worker.i: src/communication/zmq_worker.cc.i
.PHONY : src/communication/zmq_worker.i

# target to preprocess a source file
src/communication/zmq_worker.cc.i:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/src/communication/zmq_worker.cc.i
.PHONY : src/communication/zmq_worker.cc.i

src/communication/zmq_worker.s: src/communication/zmq_worker.cc.s
.PHONY : src/communication/zmq_worker.s

# target to generate assembly for a file
src/communication/zmq_worker.cc.s:
	$(MAKE) -f CMakeFiles/communication.dir/build.make CMakeFiles/communication.dir/src/communication/zmq_worker.cc.s
.PHONY : src/communication/zmq_worker.cc.s

src/main/main.o: src/main/main.cc.o
.PHONY : src/main/main.o

# target to build an object file
src/main/main.cc.o:
	$(MAKE) -f CMakeFiles/roboime-control.dir/build.make CMakeFiles/roboime-control.dir/src/main/main.cc.o
.PHONY : src/main/main.cc.o

src/main/main.i: src/main/main.cc.i
.PHONY : src/main/main.i

# target to preprocess a source file
src/main/main.cc.i:
	$(MAKE) -f CMakeFiles/roboime-control.dir/build.make CMakeFiles/roboime-control.dir/src/main/main.cc.i
.PHONY : src/main/main.cc.i

src/main/main.s: src/main/main.cc.s
.PHONY : src/main/main.s

# target to generate assembly for a file
src/main/main.cc.s:
	$(MAKE) -f CMakeFiles/roboime-control.dir/build.make CMakeFiles/roboime-control.dir/src/main/main.cc.s
.PHONY : src/main/main.cc.s

src/model/action.o: src/model/action.cc.o
.PHONY : src/model/action.o

# target to build an object file
src/model/action.cc.o:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/action.cc.o
.PHONY : src/model/action.cc.o

src/model/action.i: src/model/action.cc.i
.PHONY : src/model/action.i

# target to preprocess a source file
src/model/action.cc.i:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/action.cc.i
.PHONY : src/model/action.cc.i

src/model/action.s: src/model/action.cc.s
.PHONY : src/model/action.s

# target to generate assembly for a file
src/model/action.cc.s:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/action.cc.s
.PHONY : src/model/action.cc.s

src/model/robot.o: src/model/robot.cc.o
.PHONY : src/model/robot.o

# target to build an object file
src/model/robot.cc.o:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/robot.cc.o
.PHONY : src/model/robot.cc.o

src/model/robot.i: src/model/robot.cc.i
.PHONY : src/model/robot.i

# target to preprocess a source file
src/model/robot.cc.i:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/robot.cc.i
.PHONY : src/model/robot.cc.i

src/model/robot.s: src/model/robot.cc.s
.PHONY : src/model/robot.s

# target to generate assembly for a file
src/model/robot.cc.s:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/robot.cc.s
.PHONY : src/model/robot.cc.s

src/model/world.o: src/model/world.cc.o
.PHONY : src/model/world.o

# target to build an object file
src/model/world.cc.o:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/world.cc.o
.PHONY : src/model/world.cc.o

src/model/world.i: src/model/world.cc.i
.PHONY : src/model/world.i

# target to preprocess a source file
src/model/world.cc.i:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/world.cc.i
.PHONY : src/model/world.cc.i

src/model/world.s: src/model/world.cc.s
.PHONY : src/model/world.s

# target to generate assembly for a file
src/model/world.cc.s:
	$(MAKE) -f CMakeFiles/model.dir/build.make CMakeFiles/model.dir/src/model/world.cc.s
.PHONY : src/model/world.cc.s

src/util/config.o: src/util/config.cc.o
.PHONY : src/util/config.o

# target to build an object file
src/util/config.cc.o:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/config.cc.o
.PHONY : src/util/config.cc.o

src/util/config.i: src/util/config.cc.i
.PHONY : src/util/config.i

# target to preprocess a source file
src/util/config.cc.i:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/config.cc.i
.PHONY : src/util/config.cc.i

src/util/config.s: src/util/config.cc.s
.PHONY : src/util/config.s

# target to generate assembly for a file
src/util/config.cc.s:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/config.cc.s
.PHONY : src/util/config.cc.s

src/util/pid_controller.o: src/util/pid_controller.cc.o
.PHONY : src/util/pid_controller.o

# target to build an object file
src/util/pid_controller.cc.o:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/pid_controller.cc.o
.PHONY : src/util/pid_controller.cc.o

src/util/pid_controller.i: src/util/pid_controller.cc.i
.PHONY : src/util/pid_controller.i

# target to preprocess a source file
src/util/pid_controller.cc.i:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/pid_controller.cc.i
.PHONY : src/util/pid_controller.cc.i

src/util/pid_controller.s: src/util/pid_controller.cc.s
.PHONY : src/util/pid_controller.s

# target to generate assembly for a file
src/util/pid_controller.cc.s:
	$(MAKE) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/src/util/pid_controller.cc.s
.PHONY : src/util/pid_controller.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... communication"
	@echo "... edit_cache"
	@echo "... model"
	@echo "... rebuild_cache"
	@echo "... roboime-control"
	@echo "... util"
	@echo "... src/communication/usb_worker.o"
	@echo "... src/communication/usb_worker.i"
	@echo "... src/communication/usb_worker.s"
	@echo "... src/communication/zmq_worker.o"
	@echo "... src/communication/zmq_worker.i"
	@echo "... src/communication/zmq_worker.s"
	@echo "... src/main/main.o"
	@echo "... src/main/main.i"
	@echo "... src/main/main.s"
	@echo "... src/model/action.o"
	@echo "... src/model/action.i"
	@echo "... src/model/action.s"
	@echo "... src/model/robot.o"
	@echo "... src/model/robot.i"
	@echo "... src/model/robot.s"
	@echo "... src/model/world.o"
	@echo "... src/model/world.i"
	@echo "... src/model/world.s"
	@echo "... src/util/config.o"
	@echo "... src/util/config.i"
	@echo "... src/util/config.s"
	@echo "... src/util/pid_controller.o"
	@echo "... src/util/pid_controller.i"
	@echo "... src/util/pid_controller.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

